language: objective-c
xcode_project: PhotosPicker.xcodeproj # path to your xcodeproj folder
xcode_scheme: PhotosPicker
xcode_sdk: iphonesimulator9.3
osx_image: xcode7.3
branches:
  only:
    - master
before_install:
    - perl allowAccess
script: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme PhotosPicker -project ./PhotosPicker.xcodeproj -sdk iphonesimulator9.3 -destination platform='iOS Simulator','OS=9.3',name='iPhone 5' build test | xcpretty
