language: objective-c
xcode_project: PhotosPicker.xcodeproj # path to your xcodeproj folder
xcode_scheme: PhotosPicker
xcode_sdk: iphonesimulator9.3
osx_image: xcode7.3
branches:
  only:
    - master
