language: objective-c
xcode_project: PhotosPicker.xcodeproj # path to your xcodeproj folder
xcode_scheme: PhotosPicker

before_install:
    - perl allowAccess
    - xcrun simctl list
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -scheme PhotosPicker -project ./PhotosPicker.xcodeproj -sdk iphonesimulator -destination "OS=9.3,name=iPhone 5" clean build | xcpretty -c || true
  - xcodebuild -scheme PhotosPicker -project ./PhotosPicker.xcodeproj -sdk iphonesimulator -destination "OS=9.3,name=iPhone 5" test | xcpretty -c
